
all: install_fr.html install_en.html home_fr.html home_en.html

install_fr.html: install_fr.md
	github-markup install_fr.md >install_fr.html

install_en.html: install_en.md
	github-markup install_en.md >install_en.html

home_fr.html: home_fr.md
	github-markup home_fr.md >home_fr.html

home_en.html: home_en.md
	github-markup home_en.md >home_en.html

