#! /bin/sh

set -e

# Source debconf library.
. /usr/share/debconf/confmodule
db_title AlternC

db_reset alternc/welcomeconfirm || true
db_fset alternc/welcomeconfirm "seen" "false" || true
db_input medium alternc/welcomeconfirm || true

db_go
# Check the answer.
db_get alternc/welcomeconfirm || true

if [ "$RET" = "false" ]; then
	exit -1
fi

# default values for local.sh
MYSQL_HOST=127.0.0.1
MYSQL_DATABASE=alternc
MYSQL_USER=sysusr
MYSQL_PASS=`perl -e 'print map{("a".."z","A".."Z",0..9)[int(rand(62))]}(1..10)' `
FQDN=`hostname -f`
#INTERNAL_IP=`perl -e "print gethostbyname('$FQDN')"`
INTERNAL_IP=`/sbin/ifconfig|grep "inet addr:" | grep -v 127.0.0.1| head -1 | sed -e 's/^.*addr:\([0-9\.]*\).*$/\1/'`
DEFAULT_MX=`cat /etc/mailname`
ALTERNC_LOC='/var/alternc'
FQDN=`hostname -f`
NS1_HOSTNAME="$FQDN"
NS2_HOSTNAME="$FQDN"

if [ -r /etc/alternc/local.sh ]; then
    # source the current config
    . /etc/alternc/local.sh
fi

# mettre les valeurs de local.sh comme "default" pour debconf
db_set alternc/hostingname "$HOSTING"
db_set alternc/desktopname "$FQDN"
db_set alternc/public_ip "$PUBLIC_IP"
db_set alternc/internal_ip "$INTERNAL_IP"
db_set alternc/monitor_ip "$MONITOR_IP"
db_set alternc/ns1 "$NS1_HOSTNAME"
db_set alternc/ns2 "$NS2_HOSTNAME"
db_set alternc/bind_internal "$BIND_INTERNAL"
db_set alternc/default_mx "$DEFAULT_MX"
db_set alternc/mysql/host "$MYSQL_HOST"
db_set alternc/mysql/db "$MYSQL_DATABASE"
db_set alternc/mysql/user "$MYSQL_USER"
db_set alternc/mysql/password "$MYSQL_PASS"
db_set alternc/alternc_location "$ALTERNC_LOC"
db_set alternc/mynetwork "$SMTP_RELAY_NETWORKS"

db_input medium alternc/desktopname || true
db_input medium alternc/hostingname || true
db_input medium alternc/internal_ip || true
db_input medium alternc/public_ip || true
db_input medium alternc/default_mx || true
db_input medium alternc/ns1 || true
db_input medium alternc/ns2 || true
db_input medium alternc/alternc_location || true
db_input low alternc/mysql/host || true
db_input low alternc/mysql/db || true
db_input low alternc/mysql/user || true
db_input low alternc/mysql/password || true
db_input low alternc/monitor_ip || true
db_input low alternc/bind_internal || true
db_input low alternc/mynetwork || true
db_go

# vim: et sw=4
